#!/usr/bin/env python3
"""Generates src/profile_generated.zig from Garmin's FIT Python SDK.

Usage:
    git clone --depth 1 https://github.com/garmin/fit-python-sdk /tmp/fit-python-sdk
    tools/profile_generate.py /tmp/fit-python-sdk > src/profile_generated.zig
    zig fmt src/profile_generated.zig

The SDK's profile.py is a Python dict generated by Garmin from Profile.xlsx, with snake_case
names. This keeps messages, fields (name, units, scale, offset) and the value names of the types
fields use. Subfields and components are not emitted yet.

Only this script and its output are committed; the SDK checkout is not. Run it by hand when
moving to a new profile version, then review the diff.
"""

import importlib.util
import json
import pathlib
import sys

LINE_LENGTH_MAX = 100
HEADER = """\
//! Generated by tools/profile_generate.py from profile.py of Garmin's FIT Python SDK
//! (https://github.com/garmin/fit-python-sdk), profile version {version}. Do not edit;
//! regenerate instead. profile.zig wraps these tables.
//!
//! Derived from the FIT SDK: Copyright Garmin International, Inc. Licensed under the Flexible
//! and Interoperable Data Transfer (FIT) Protocol License.
//!
//! Sorted by number (messages, fields) and by value (type values), so lookups can binary-search.

pub const version = "{version}";

pub const Kind = enum {{ number, date_time, local_date_time, semicircles }};

pub const Field = struct {{
    number: u8,
    name: []const u8,
    kind: Kind = .number,
    units: []const u8 = "",
    scale: f64 = 1,
    offset: i16 = 0,
    /// Index into `types` when the field's values have names.
    type_index: ?u16 = null,
}};

pub const Message = struct {{
    number: u16,
    name: []const u8,
    fields: []const Field,
}};

pub const ValueName = struct {{
    value: u32,
    name: []const u8,
}};

pub const Type = struct {{
    name: []const u8,
    values: []const ValueName,
}};
"""


def profile_load(sdk_path):
    path = pathlib.Path(sdk_path) / "garmin_fit_sdk" / "profile.py"
    spec = importlib.util.spec_from_file_location("profile", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.Profile


def zig_string(text):
    assert all(ord(character) >= 0x20 and character != "\x7f" for character in text), text
    # JSON escapes quotes and backslashes the way Zig does; non-ASCII stays as UTF-8.
    return json.dumps(text, ensure_ascii=False)


def zig_float(value):
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def field_kind(field):
    if field["type"] == "date_time":
        return "date_time"
    if field["type"] == "local_date_time":
        return "local_date_time"
    if field["units"] in ("semicircles", ["semicircles"]) and field["base_type"] == "sint32":
        return "semicircles"
    return "number"


def field_scaling(field):
    """A field with several scales, units or offsets holds components, which are scaled one by
    one, not as a whole; like the SDK decoder, the field itself is then left unscaled."""
    scales, offsets, units = field["scale"], field["offset"], field["units"]
    # Units are a string, or a list with one entry per component.
    if isinstance(units, list):
        units = units[0] if len(units) == 1 else ""
    if len(scales) != 1:
        assert field["components"], field["name"]
        return 1, 0, ""
    assert len(offsets) == 1, field["name"]
    return scales[0], offsets[0], units


def field_entry(field, type_indexes):
    kind = field_kind(field)
    scale, offset, units = field_scaling(field)
    assert scale > 0, field["name"]
    assert -(2**15) <= offset < 2**15, field["name"]
    parts = [f".number = {field['num']}", f".name = {zig_string(field['name'])}"]
    if kind != "number":
        # A converted field is never scaled; the conversion replaces scale and offset.
        assert scale == 1 and offset == 0, field["name"]
        parts.append(f".kind = .{kind}")
    if kind in ("date_time", "local_date_time"):
        # A date's raw value counts seconds, though the SDK leaves the unit off some dates.
        assert units in ("", "s", "seconds"), field["name"]
        units = "s"
    if units:
        parts.append(f".units = {zig_string(units)}")
    if scale != 1:
        parts.append(f".scale = {zig_float(scale)}")
    if offset != 0:
        parts.append(f".offset = {offset}")
    # A date's type table only names a sentinel ("min"); the conversion handles dates.
    if kind == "number" and field["type"] in type_indexes:
        parts.append(f".type_index = {type_indexes[field['type']]}")
    return parts


def struct_write(lines, indent, parts):
    """One line when it fits; otherwise one part per line, which zig fmt keeps."""
    line = " " * indent + ".{ " + ", ".join(parts) + " },"
    if len(line) <= LINE_LENGTH_MAX:
        lines.append(line)
        return
    lines.append(" " * indent + ".{")
    lines.extend(" " * (indent + 4) + part + "," for part in parts)
    lines.append(" " * indent + "},")


def used_types(profile):
    names = set()
    for message in profile["messages"].values():
        for field in message["fields"].values():
            # Some types, like localtime_into_day, name no values at all.
            if field_kind(field) == "number" and profile["types"].get(field["type"]):
                names.add(field["type"])
    return sorted(names)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    profile = profile_load(sys.argv[1])
    version = profile["version"]
    version_text = f"{version['major']}.{version['minor']}.{version['patch']}"
    types = used_types(profile)
    type_indexes = {name: index for index, name in enumerate(types)}
    assert len(types) < 2**16

    lines = [HEADER.format(version=version_text), "pub const messages = [_]Message{"]
    for number in sorted(profile["messages"]):
        message = profile["messages"][number]
        assert 0 <= number < 2**16
        lines.append(f"    .{{ .number = {number}, .name = {zig_string(message['name'])}, "
                     ".fields = &.{")
        for field_number in sorted(message["fields"]):
            field = message["fields"][field_number]
            assert field["num"] == field_number and 0 <= field_number < 2**8
            struct_write(lines, 8, field_entry(field, type_indexes))
        lines.append("    } },")
    lines.append("};")
    lines.append("")
    lines.append("pub const types = [_]Type{")
    for name in types:
        lines.append(f"    .{{ .name = {zig_string(name)}, .values = &.{{")
        for value in sorted(profile["types"][name]):
            assert 0 <= int(value) < 2**32
            value_name = profile["types"][name][value]
            struct_write(lines, 8, [f".value = {value}", f".name = {zig_string(value_name)}"])
        lines.append("    } },")
    lines.append("};")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
