#!/usr/bin/env python3
"""Generates src/profile_generated.zig from Garmin's FIT Python SDK.

Usage:
    git clone --depth 1 https://github.com/garmin/fit-python-sdk /tmp/fit-python-sdk
    tools/profile_generate.py /tmp/fit-python-sdk > src/profile_generated.zig
    zig fmt src/profile_generated.zig

The SDK's profile.py is a Python dict generated by Garmin from Profile.xlsx, with snake_case
names. This keeps messages, fields (name, units, scale, offset), their subfields (the same, plus
the field values that select them) and the value names of the types they use. Components are not
emitted yet.

Only this script and its output are committed; the SDK checkout is not. Run it by hand when
moving to a new profile version, then review the diff.
"""

import importlib.util
import json
import pathlib
import sys

LINE_LENGTH_MAX = 100
HEADER = """\
//! Generated by tools/profile_generate.py from profile.py of Garmin's FIT Python SDK
//! (https://github.com/garmin/fit-python-sdk), profile version {version}. Do not edit;
//! regenerate instead. profile.zig wraps these tables.
//!
//! Derived from the FIT SDK: Copyright Garmin International, Inc. Licensed under the Flexible
//! and Interoperable Data Transfer (FIT) Protocol License.
//!
//! Sorted by number (messages, fields) and by value (type values), so lookups can binary-search.

pub const version = "{version}";

pub const Kind = enum {{ number, date_time, local_date_time, semicircles }};

pub const Field = struct {{
    number: u8,
    name: []const u8,
    kind: Kind = .number,
    units: []const u8 = "",
    scale: f64 = 1,
    offset: i16 = 0,
    /// Index into `types` when the field's values have names.
    type_index: ?u16 = null,
    /// Other meanings of the field, each chosen by the value of another field in the message.
    subfields: []const Subfield = &.{{}},
}};

/// A field's alternative meaning, active when any of its references matches. Subfields keep
/// the SDK's order, because when several match (a running session with sub_sport 20 matches
/// both total_strides and total_reps), the first one applies.
pub const Subfield = struct {{
    name: []const u8,
    kind: Kind = .number,
    units: []const u8 = "",
    scale: f64 = 1,
    offset: i16 = 0,
    type_index: ?u16 = null,
    references: []const Reference,
}};

/// The subfield applies when field `field_number` of the same message holds `value`, raw.
pub const Reference = struct {{
    field_number: u8,
    value: u16,
}};

pub const Message = struct {{
    number: u16,
    name: []const u8,
    fields: []const Field,
}};

pub const ValueName = struct {{
    value: u32,
    name: []const u8,
}};

/// A type whose values are names (an enumeration), or, when `mask` is nonzero, a bit field: the
/// number under `mask` plus the single-bit flags in `values`.
pub const Type = struct {{
    name: []const u8,
    mask: u32 = 0,
    values: []const ValueName,
}};
"""


def profile_load(sdk_path):
    path = pathlib.Path(sdk_path) / "garmin_fit_sdk" / "profile.py"
    spec = importlib.util.spec_from_file_location("profile", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.Profile


def zig_string(text):
    assert all(ord(character) >= 0x20 and character != "\x7f" for character in text), text
    # JSON escapes quotes and backslashes the way Zig does; non-ASCII stays as UTF-8.
    return json.dumps(text, ensure_ascii=False)


def zig_float(value):
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def field_kind(field, base_type):
    if field["type"] == "date_time":
        return "date_time"
    if field["type"] == "local_date_time":
        return "local_date_time"
    if field["units"] in ("semicircles", ["semicircles"]) and base_type == "sint32":
        return "semicircles"
    return "number"


def field_scaling(field):
    """A field with several scales, units or offsets holds components, which are scaled one by
    one, not as a whole; like the SDK decoder, the field itself is then left unscaled."""
    scales, offsets, units = field["scale"], field["offset"], field["units"]
    # Units are a string, or a list with one entry per component.
    if isinstance(units, list):
        units = units[0] if len(units) == 1 else ""
    if len(scales) != 1:
        assert field["components"], field["name"]
        return 1, 0, ""
    assert len(offsets) == 1, field["name"]
    return scales[0], offsets[0], units


def profile_parts(field, base_type, type_indexes):
    """The parts a field and a subfield share: a subfield has no number and no base type of its
    own, so it takes its field's."""
    kind = field_kind(field, base_type)
    scale, offset, units = field_scaling(field)
    assert scale > 0, field["name"]
    assert -(2**15) <= offset < 2**15, field["name"]
    parts = [f".name = {zig_string(field['name'])}"]
    if kind != "number":
        # A converted field is never scaled; the conversion replaces scale and offset.
        assert scale == 1 and offset == 0, field["name"]
        parts.append(f".kind = .{kind}")
    if kind in ("date_time", "local_date_time"):
        # A date's raw value counts seconds, though the SDK leaves the unit off some dates.
        assert units in ("", "s", "seconds"), field["name"]
        units = "s"
    if units:
        parts.append(f".units = {zig_string(units)}")
    if scale != 1:
        parts.append(f".scale = {zig_float(scale)}")
    if offset != 0:
        parts.append(f".offset = {offset}")
    # A date's type table only names a sentinel ("min"); the conversion handles dates.
    if kind == "number" and field["type"] in type_indexes:
        parts.append(f".type_index = {type_indexes[field['type']]}")
    return parts


def subfield_references(message, field, subfield):
    """A reference names a single-value field of the same message whose values fit a u16, so a
    raw value can be compared directly."""
    references = []
    for entry in subfield["map"]:
        referenced = message["fields"][entry["num"]]
        assert referenced["name"] == entry["name"], entry
        assert referenced["array"] == "false", entry
        assert referenced["base_type"] in ("enum", "uint8", "uint16"), entry
        assert entry["num"] != field["num"], entry
        assert 0 <= entry["raw_value"] < 2**16, entry
        references.append((entry["num"], entry["raw_value"]))
    assert references, subfield["name"]
    return references


def subfields_check(message, field):
    """A reference an earlier subfield of the same field already has would never select this
    one, since the first match applies: that would be dead profile data."""
    seen = {}
    for subfield in field["sub_fields"]:
        for reference in subfield_references(message, field, subfield):
            assert reference not in seen, (field["name"], seen.get(reference), subfield["name"])
            seen[reference] = subfield["name"]


def field_write(lines, message, field, type_indexes):
    parts = [f".number = {field['num']}"]
    parts += profile_parts(field, field["base_type"], type_indexes)
    if not field["sub_fields"]:
        struct_write(lines, 8, parts)
        return
    subfields_check(message, field)
    lines.append(" " * 8 + ".{")
    lines.extend(" " * 12 + part + "," for part in parts)
    lines.append(" " * 12 + ".subfields = &.{")
    for subfield in field["sub_fields"]:
        subfield_parts = profile_parts(subfield, field["base_type"], type_indexes)
        lines.append(" " * 16 + ".{")
        lines.extend(" " * 20 + part + "," for part in subfield_parts)
        lines.append(" " * 20 + ".references = &.{")
        for number, value in subfield_references(message, field, subfield):
            lines.append(" " * 24 + f".{{ .field_number = {number}, .value = {value} }},")
        lines.append(" " * 20 + "},")
        lines.append(" " * 16 + "},")
    lines.append(" " * 12 + "},")
    lines.append(" " * 8 + "},")


def struct_write(lines, indent, parts):
    """One line when it fits; otherwise one part per line, which zig fmt keeps."""
    line = " " * indent + ".{ " + ", ".join(parts) + " },"
    if len(line) <= LINE_LENGTH_MAX:
        lines.append(line)
        return
    lines.append(" " * indent + ".{")
    lines.extend(" " * (indent + 4) + part + "," for part in parts)
    lines.append(" " * indent + "},")


def type_split(values):
    """A type with a value named "mask" is a bit field (message_index, left_right_balance): the
    number under the mask, plus single-bit flags. Its "mask" and "reserved" entries describe the
    layout, not values, so only the flags are kept."""
    masks = [value for value, name in values.items() if name == "mask"]
    if not masks:
        return 0, values
    assert len(masks) == 1
    mask = masks[0]
    flags = {value: name for value, name in values.items() if name not in ("mask", "reserved")}
    assert 1 <= len(flags) <= 4, flags
    for flag in flags:
        # Each flag is one bit, outside the number.
        assert flag & (flag - 1) == 0 and flag & mask == 0, flags
    return mask, flags


def used_types(profile):
    names = set()
    for message in profile["messages"].values():
        for field in message["fields"].values():
            for entry in [field] + field["sub_fields"]:
                # Some types, like localtime_into_day, name no values at all.
                kind = field_kind(entry, field["base_type"])
                if kind == "number" and profile["types"].get(entry["type"]):
                    names.add(entry["type"])
    return sorted(names)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    profile = profile_load(sys.argv[1])
    version = profile["version"]
    version_text = f"{version['major']}.{version['minor']}.{version['patch']}"
    types = used_types(profile)
    type_indexes = {name: index for index, name in enumerate(types)}
    assert len(types) < 2**16

    lines = [HEADER.format(version=version_text), "pub const messages = [_]Message{"]
    for number in sorted(profile["messages"]):
        message = profile["messages"][number]
        assert 0 <= number < 2**16
        lines.append(f"    .{{ .number = {number}, .name = {zig_string(message['name'])}, "
                     ".fields = &.{")
        for field_number in sorted(message["fields"]):
            field = message["fields"][field_number]
            assert field["num"] == field_number and 0 <= field_number < 2**8
            field_write(lines, message, field, type_indexes)
        lines.append("    } },")
    lines.append("};")
    lines.append("")
    lines.append("pub const types = [_]Type{")
    for name in types:
        mask, values = type_split(profile["types"][name])
        mask_part = f".mask = 0x{mask:X}, " if mask else ""
        lines.append(f"    .{{ .name = {zig_string(name)}, {mask_part}.values = &.{{")
        for value in sorted(values):
            assert 0 <= int(value) < 2**32
            struct_write(lines, 8, [f".value = {value}", f".name = {zig_string(values[value])}"])
        lines.append("    } },")
    lines.append("};")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
